[2022-06-03 21:05:53,432] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: UK_COVID19_dag.Scale_UK_Data 2022-06-02T20:58:06.025617+00:00 [queued]>
[2022-06-03 21:05:53,487] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: UK_COVID19_dag.Scale_UK_Data 2022-06-02T20:58:06.025617+00:00 [queued]>
[2022-06-03 21:05:53,493] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 21:05:53,495] {taskinstance.py:1043} INFO - Starting attempt 3 of 4
[2022-06-03 21:05:53,496] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 21:05:53,522] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): Scale_UK_Data> on 2022-06-02T20:58:06.025617+00:00
[2022-06-03 21:05:53,531] {standard_task_runner.py:52} INFO - Started process 60 to run task
[2022-06-03 21:05:53,548] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'UK_COVID19_dag', 'Scale_UK_Data', '2022-06-02T20:58:06.025617+00:00', '--job-id', '6', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/covid_dag-checkpoint.py', '--cfg-path', '/tmp/tmp3lpzcot4', '--error-file', '/tmp/tmps5_p7h53']
[2022-06-03 21:05:53,550] {standard_task_runner.py:77} INFO - Job 6: Subtask Scale_UK_Data
[2022-06-03 21:05:53,644] {logging_mixin.py:104} INFO - Running <TaskInstance: UK_COVID19_dag.Scale_UK_Data 2022-06-02T20:58:06.025617+00:00 [running]> on host 125d245880e1
[2022-06-03 21:05:53,730] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Huda
AIRFLOW_CTX_DAG_ID=UK_COVID19_dag
AIRFLOW_CTX_TASK_ID=Scale_UK_Data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-02T20:58:06.025617+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-02T20:58:06.025617+00:00
[2022-06-03 21:05:55,823] {python.py:118} INFO - Done. Returned value was: None
[2022-06-03 21:05:55,894] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=UK_COVID19_dag, task_id=Scale_UK_Data, execution_date=20220602T205806, start_date=20220603T210553, end_date=20220603T210555
[2022-06-03 21:05:55,994] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-06-03 21:05:56,120] {local_task_job.py:146} INFO - Task exited with return code 0
